homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data
  elevation: 162.20
  # C for Celsius, F for Fahrenheit
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto

  customize: !include customize.yaml

     

# Allows you to issue voice commands from the frontend
conversation:

# View all events in a logbook
logbook:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# Track the sun
sun:

logger:
  default: critical
#   logs:    
#     homeassistant.components.lock.zwave: info
   

config:  

group: !include groups.yaml

  
http:
  api_password: !secret http_password
  ssl_certificate: !secret fullchain 
  ssl_key: !secret privkey 

automation: !include automations.yaml
#automation old: !include locks.yaml

# ecobee:
#   api_key: !secret ecobee_api_key

lutron_caseta:
  host: 192.168.1.22


#nest:
#  client_id: !secret nest_client_id
#  client_secret: !secret nest_client_secret

cover:
  - platform: myq
    username: !secret cover_myd_username 
    password: !secret cover_myd_password
    type: chamberlain  

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_key
    latitude: !secret work_lat
    longitude: !secret work_long


zwave:
  device_config: !include zwave_device_config.yaml
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 30000
  new_entity_ids: true
  # customize:
  #   sensor.greenwave_powernode_6_port_energy_10:
  #       polling_intensity: 1


# Text to speech
tts:
  platform: google


mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: p25
  password:  !secret mqtt_password
  

device_tracker:
- platform: asuswrt
  host: 192.168.1.1 
  protocol: telnet
  mode: router
  username: admin
  password: !secret asuswrt_password
  consider_home: 600
- platform: owntracks
  max_gps_accuracy: 200
  waypoints: true
  waypoint_whitelist: androids7
  consider_home: 600


zone:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 35
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret work_lat
  longitude: !secret work_long
  radius: 100
  icon: mdi:briefcase



script: !include scripts.yaml

sensor: !include sensors.yaml



shell_command: 
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01 && sudo reboot

google_assistant:
  project_id: homeassistant-142504
  client_id: uxPIFIPFeXMcAhymh1XjrH8aTHFCKOM4LmYH2RkBAN5q8YQVJaVCejzPzuThgy5HmpJVnzsIJcIAeUdg
  access_token: MLR95N7KXUv3yZW3fJkpKFlv8WRhzqGljuOv3m3uvu4JVjYws3o1A3CDWeElFe4av4CfZGXrL3OUDKlg
  # exposed_domains:
  #   - switch
  #   - light
  #   - group
  #   - cover