- alias: Unlock Door when Aaron or Robyn comes home
  trigger:
    platform: state
    entity_id: device_tracker.pi_androids72, device_tracker.android91483e59a00937ff
    # Optional 
    #state: 'xy'
    # or (don't use that with condition: use_trigger_values)
    from: 'not_home'
    to: 'home'
  condition: 
  - condition: and
    conditions:
      - condition: time
        before: '23:59'
      - condition: time
        after: '09:00'
  action:
    service: script.unlock_door


- alias: Relock Door 5 minutes after opening 
  trigger:
    platform: state
    entity_id: lock.schlage_be469nxcen_touchscreen_deadbolt_locked_2_0
    # Optional 
    # state: 'locked'
    # or (don't use that with condition: use_trigger_values)
    from: 'locked'
    to: 'unlocked'
  action:
    service: script.timer_relock  





- alias: Turn on outdoor lights if Aaron or Robyn leave after dark
  trigger:
    platform: state
    entity_id: device_tracker.pi_androids72, device_tracker.android91483e59a00937ff
    # Optional 
    #state: 'xy'
    # or (don't use that with condition: use_trigger_values)
    from: 'home'
    to: 'not_home'
  condition: 
  - condition: or
    conditions:  
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise  
  action:
    service: switch.turn_on
    entity_id: switch.out_door_lights_switch_3_0

- alias: Turn on outdoor lights if Aaron or Robyn are not home when the sun sets
  trigger:
    platform: sun
    event: sunset
  condition: 
  - condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise  
    - condition: state
      entity_id: sensor.aaron_home
      state: 'False'
    - condition: state
      entity_id: sensor.robyn_home
      state: 'False'  
  action:
    service: switch.turn_on
    entity_id: switch.out_door_lights_switch_3_0

- alias: Turn off outdoor lights when the sun rises
  trigger:
    platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: switch.out_door_lights_switch_3_0    

- alias: Turn off outdoor lights if Aaron or Robyn are both home
  trigger:
    platform: state
    entity_id: device_tracker.pi_androids72, device_tracker.android91483e59a00937ff
    # Optional 
    #state: 'xy'
    # or (don't use that with condition: use_trigger_values)
    from: 'not_home'
    to: 'home' 
  condition:  
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.pi_androids72 
      state: 'home'
    - condition: state
      entity_id: device_tracker.android91483e59a00937ff
      state: 'home'      
  action:
    service: switch.turn_off
    entity_id: switch.out_door_lights_switch_3_0   








# - alias: soft reset at 2:30am
#   trigger:
#     platform: time
#     after: '2:30:00'
#   action:
#     service: zwave.soft_reset

# - alias: heal at 2:31am
#   trigger:
#     platform: time
#     after: '2:31:00'
#   action:
#     service: zwave.heal_network