
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use

- platform: fastdotcom
  minute:
    - 0
    - 15
    - 30
    - 45
    
- platform: yr      