
- platform: template
  sensors:
    aaron_home:
      friendly_name: 'Is Aaron home?'
      value_template: '{% if states("device_tracker.pi_androids72") != "home" %}false{% else %}true{% endif %}'
    robyn_home:
      friendly_name: 'Is Robyn home?'
      value_template: '{% if states("device_tracker.android1c713e06860501c3") != "home" %}false{% else %}true{% endif %}'  


- platform: cert_expiry
  host: ennerdale.duckdns.org

- platform: speedtest
  minute:
    - 7
    - 22
    - 37
    - 52
  monitored_conditions:
    - ping
    - download

